pipeline:

  - step:
      from: 
        table: stg.gtfs__stops
        options:
          geometry: geom
      with:
        table: stg.ovm__places
        options:
          geometry: geom
          id: id
      function:
        type: aggregate_within_buffer
        options:
          buffer_size: 300
          agg: "count(id) AS poi_count"
      to:
        table: stg.gtfs__stops_agg_buffer
