pipeline:


  - step:
      from: 
        table: stg.gtfs__stops
        options:
          geometry: geom
      with:
        table: stg.ovm__places
        options:
          geometry: geom
          id: id
      function:
        type: aggregate_within_buffer
        options:
          buffer_size: 300
          agg: "count(id) AS poi_count"
      to:
        table: stg.gtfs__stops_agg_buffer

  - step:
      from: 
        table: stg.gtfs__stops
        options:
          geometry: geom
      function:
        type: generate_buffer
        options:
          size: 300
          column: buffer_geom
      to:
        table: stg.gtfs__stops_buffer_300

  - step:
      from:
        table: stg.gtfs__stops_buffer_300
        options: 
          geometry: buffer_geom
      with:
        table: stg.geoboundaries__adm3
        options:
          geometry: geom
      function:
        type: filter_by_overlap
        options:
          where: "shape_name = 'Brno'"
      to:
        table: stg.gtfs__stops_brno

  - step:
      from:
        table: stg.worldpop__population
        options: 
          geometry: geom
      with:
        table: stg.gtfs__stops_buffer_300
        options:
          geometry: buffer_geom
      function:
        type: aggregate_by_region
        options: 
          agg: "SUM(pop) AS total_pop"
      to:
        table: stg.stops_pop_300

  - step:
      from:
        table: stg.gtfs__stops
        options: 
          geometry: geom
      function:
        type: generate_grid_h3
        options:
          h3_res: 6
      to:
        table: stg.gtfs__stops_grid

  - step:
      from:
        table: stg.gtfs__stops
        options: 
          geometry: geom
          id: stop_id
      with:
        table: stg.ovm__places
        options:
          geometry: geom
          id: id
      function:
        type: find_nearest_neighbors
        options:
          max_distance: 2000
          max_neighbours: 3
      to:
        table: stg.gtfs__stops_places_nearest

  - step:
      from:
        table: stg.gtfs__stops
        options: 
          geometry: geom
          columns:
            - "stop_id"
      with:
        table: stg.geoboundaries__adm3
        options:
          geometry: geom
          columns:
            - "shape_name AS adm_name"
      function:
        type: enrich_by_overlap
        options: {}
      to:
        table: stg.gtfs__stops_adm3
  
  - step:
      function:
        type: custom_sql_file
        options:
          sql_file_path: ./sql/custom.sql

  - step:
      function:
        type: custom_sql
        options:
          sql: |
            select count(1) from stg.gtfs__stops_adm3
